### ISSUE TITLE
Add toolbar icon with dropdown menu

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/AppLayoutAddon#42]
Provide a toolbar icon with dropdown menu

**Comment by javier-godoy** [comment]
Since vcf-popup [is now open source](https://github.com/vaadin-component-factory/vcf-popup/commit/c85a79cbcac592c37bf14a08c56e9c5784166e61#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7), we can implement this feature based on that component.

**Comment by mlopezFC** [comment]
Given that it's possible to add arbitrary components to the toolbar (since [this commit](https://github.com/FlowingCode/AppLayoutAddon/commit/78fd914840dd7f1ce657807146a4f6fb017398a5#diff-a248fb47183cb759e606e535dc8dfebdec79eafbf9d286d18f509e32ac3d1cf9L67-R68)), this can be implemented outside this addon.
