### ISSUE TITLE
Consider replacing MenuItem with Accordion

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/AppLayoutAddon#50]
Nested MenuItems are basically nested Accordions modulo some differences. It would be nice to replace our custom implementation of fc-menuitem with vaadin-accordion (or document what features prevent us from doing so)

**Comment by mlopezFC** [comment]
I think that fc-menuitem is a better implementation because it allows nested hierarchies and also has a nice animation when opening/closing.
In fact with an empty menu and with [this method](https://github.com/FlowingCode/AppLayoutAddon/blob/v4.x/src/main/java/com/flowingcode/addons/applayout/AppLayout.java#L89), it already should be possible to provide an accordion or another component.

**Comment by javier-godoy** [comment]
I agree.
